version: "2"
linters:
  enable:
    - bodyclose
    - dogsled
    - goconst
    - gocritic
    - goprintffuncname
    - gosec
    - importas
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - forbidigo
    - gochecknoinits
  settings:
    forbidigo:
      forbid:
        - pattern: ^(fmt\.Print(|f|ln)|print|println)$
          msg: in cli package use `feedback.*` instead
        - pattern: (os\.(Stdout|Stderr|Stdin))(# )?
          msg: in cli package use `feedback.*` instead
      analyze-types: true
    misspell:
      locale: US
    revive:
      rules:
        - name: indent-error-flow
          disabled: true
    goconst:
      ignore-string-values:
        - ".exe"
        - "windows"
        - "linux"
        - "darwin"

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - path: cmd/arduino-app-cli/*_test.go
        linters:
          - forbidigo
      - path: cmd/feedback/
        linters:
          - forbidigo
      - path: cmd/gendoc/
        linters:
          - forbidigo
      - path: pkg/board/remote/adb
        linters:
          - forbidigo
      - path: internal/e2e
        linters:
          - forbidigo
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/arduino/arduino-app-cli
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
