# EI_OBJ_DETECTION_MODEL = path to the model file
# CUSTOM_MODEL_PATH = path to the custom model directory
services:
  ei-video-obj-detection-runner:
    image: ${DOCKER_REGISTRY_BASE:-public.ecr.aws/arduino/}app-bricks/ei-models-runner:0.4.2   
    ports:
      - ${BIND_PORT:-4912}:4912
    volumes:
      - "${CUSTOM_MODEL_PATH:-/home/arduino/.arduino-bricks/ei-models/}:${CUSTOM_MODEL_PATH:-/home/arduino/.arduino-bricks/ei-models/}"
      - "/run/udev:/run/udev"
    command: ["--model-file", "${EI_OBJ_DETECTION_MODEL:-/models/ootb/ei/yolo-x-nano.eim}", "--dont-print-predictions", "--mode", "streaming", "--force-target", "--preview-original-resolution", "--camera", "${VIDEO_DEVICE:-/dev/video1}"]

